<div style="
    display: grid;    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 4em;
    text-align: center;
    margin-bottom: 2em;
">
    <div style="background:#e16a6a;padding:1em;"><p style="text-shadow:1px 1px 3px rgba(0,0,0,0.4);color:white;font-weight:600;margin:0;">Test1</p></div>
    <div style="background:#5858c2;padding:1em;"><p style="text-shadow:1px 1px 3px rgba(0,0,0,0.4);color:white;font-weight:600;margin:0;">Test2</p></div>
    <div style="background:#54ae56;padding:1em;"><p style="text-shadow:1px 1px 3px rgba(0,0,0,0.4);color:white;font-weight:600;margin:0;">Test3</p></div>
    <div style="background:#42c3cd;padding:1em;"><p style="text-shadow:1px 1px 3px rgba(0,0,0,0.4);color:white;font-weight:600;margin:0;">Test4</p></div>
</div>